# This is a template file - actual secrets should be encrypted and managed securely
apiVersion: v1
kind: Secret
metadata:
  name: content-weave-secrets
  namespace: content-weave
  labels:
    app: content-weave
type: Opaque
stringData:
  # These should be base64 encoded in production
  supabase-url: "https://your-project.supabase.co"
  supabase-anon-key: "your-supabase-anon-key"
  mercadopago-public-key: "your-mercadopago-public-key"
  redis-password: "your-redis-password"
  
---
# Docker registry secret for pulling private images
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: content-weave
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    # Base64 encoded Docker config JSON
    # Generate with: kubectl create secret docker-registry ghcr-secret --docker-server=ghcr.io --docker-username=USERNAME --docker-password=TOKEN --dry-run=client -o yaml